### ISSUE TITLE
Multi-repos errors

### ISSUE THREAD

**Issue by maiis** [musically-ut/appreciate#2]
Hi,

I Appreciate it ;)

But I found a problem when multiple dependencies are from then same repository, like Facebook is doing for example here https://github.com/facebook/react/tree/master/packages and here https://github.com/facebook/jest/tree/master/packages

```
Error:  Error: node-multispinner: there are multiple spinners with ID 'facebook/jest'
```

Output the list of repos, spinnerNames:
```
[
...
  'facebook/jest',
  'facebook/react',
  'facebook/react',
  'facebook/react',
...
]
```

In my package JSON:
```
...
    "babel-jest": "16.0.0",
    "jest": "16.0.1",
    "react": "15.3.2",
    "react-dom": "15.3.2",
...
```

**Comment by musically-ut** [comment]
Thanks for reporting it!

I'll release a fix later in the day. :)
